// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCak9THU-2TWoMAiG1byk_azehNB74uk5w',
    appId: '1:198401946125:web:1cb440389c443f1980db44',
    messagingSenderId: '198401946125',
    projectId: 'talkster-da6af',
    authDomain: 'talkster-da6af.firebaseapp.com',
    storageBucket: 'talkster-da6af.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvS-jKAIMoSFsVVfAopu01MzAw-02BvIo',
    appId: '1:198401946125:android:23b9aed4b9d71b6980db44',
    messagingSenderId: '198401946125',
    projectId: 'talkster-da6af',
    storageBucket: 'talkster-da6af.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDi6v9d74P6iAm_QWuOS39XRYHuaUvqZn4',
    appId: '1:198401946125:ios:15df9d5568da7fd480db44',
    messagingSenderId: '198401946125',
    projectId: 'talkster-da6af',
    storageBucket: 'talkster-da6af.appspot.com',
    iosBundleId: 'com.example.talkster',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDi6v9d74P6iAm_QWuOS39XRYHuaUvqZn4',
    appId: '1:198401946125:ios:15df9d5568da7fd480db44',
    messagingSenderId: '198401946125',
    projectId: 'talkster-da6af',
    storageBucket: 'talkster-da6af.appspot.com',
    iosBundleId: 'com.example.talkster',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCak9THU-2TWoMAiG1byk_azehNB74uk5w',
    appId: '1:198401946125:web:1f543005b93ccd3280db44',
    messagingSenderId: '198401946125',
    projectId: 'talkster-da6af',
    authDomain: 'talkster-da6af.firebaseapp.com',
    storageBucket: 'talkster-da6af.appspot.com',
  );
}
